version: "3.9"

services:
  app:
    build: ./app
    env_file:
      - .env
    depends_on:
      db:
        condition: service_healthy
    networks:
      - payment-net

  nginx:
    image: nginx:alpine
    ports:
      - "8080:80"
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - app
    networks:
      - payment-net

  db:
    image: postgres:15
    environment:
      POSTGRES_DB: payments
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    volumes:
      - db-data:/var/lib/postgresql/data
    restart: always
    networks:
      - payment-net
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      retries: 5

  redis:
    image: redis:7
    networks:
      - payment-net

volumes:
  db-data:

networks:
  payment-net: